version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    labels:
      - "github_actions"
      - "dependencies"
    commit-message:
      prefix: ci
    open-pull-requests-limit: 10

  # Корневой package.json
  - package-ecosystem: npm
    directory: "/"
    versioning-strategy: increase
    schedule:
      interval: monthly
    labels:
      - "npm"
      - "dependencies"
    commit-message:
      prefix: deps
      prefix-development: deps-dev
    groups:
      # Инструменты разработки
      dev-tools:
        patterns:
          - "turbo"
          - "husky"
          - "lint-staged"
          - "prettier"
      # Commitlint
      commitlint:
        patterns:
          - "@commitlint/*"
      # TypeScript
      typescript:
        patterns:
          - "typescript"
          - "@types/node"
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 10

  # Frontend SSO
  - package-ecosystem: npm
    directory: "/apps/frontend/sso"
    schedule:
      interval: monthly
    labels:
      - "npm"
      - "frontend"
      - "dependencies"
    commit-message:
      prefix: deps
      prefix-development: deps-dev
    groups:
      # Next.js и React
      next-react:
        patterns:
          - "next"
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      # Линтеры и форматтеры
      lint:
        patterns:
          - "eslint"
          - "@typescript-eslint/*"
          - "stylelint"
          - "prettier"
      # TypeScript
      typescript:
        patterns:
          - "typescript"
          - "@types/node"
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]

  # Backend Gateway
  - package-ecosystem: npm
    directory: "/apps/backend/gateway"
    schedule:
      interval: monthly
    labels:
      - "npm"
      - "backend"
      - "dependencies"
    commit-message:
      prefix: deps
      prefix-development: deps-dev
    groups:
      # NestJS
      nestjs:
        patterns:
          - "@nestjs/*"
      # Тестирование
      testing:
        patterns:
          - "jest"
          - "@jest/*"
          - "@types/jest"
          - "ts-jest"
          - "supertest"
          - "@types/supertest"
      # TypeScript и инструменты
      typescript-tools:
        patterns:
          - "typescript"
          - "@types/node"
          - "ts-node"
          - "ts-loader"
          - "tsconfig-paths"
      # Линтеры и форматтеры
      lint:
        patterns:
          - "eslint"
          - "@typescript-eslint/*"
          - "prettier"
          - "prettier-plugin-*"
