global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:${PROMETHEUS_PORT}"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # NestJS Backend Metrics
  - job_name: "nestjs"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["host.docker.internal:4000"] # Adjust port based on your NestJS app

  # Redis Metrics
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  # PostgreSQL Metrics
  - job_name: "postgresql"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  # Elasticsearch Metrics
  - job_name: "elasticsearch"
    metrics_path: "/_prometheus/metrics"
    static_configs:
      - targets: ["elasticsearch:${ELASTIC_PORT}"]
