name: Branch Protection Rules

on:
  push:
    paths:
      - ".github/workflows/branch-protection.yml"
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  protection:
    name: Set Branch Protection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Branch Protection
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.LHCI_GITHUB_APP_TOKEN }} # Используем токен с правами админа
          script: |
            const { owner, repo } = context.repo;
            await github.rest.repos.updateBranchProtection({
              owner,
              repo,
              branch: 'main',
              required_status_checks: null,
              enforce_admins: true,
              required_pull_request_reviews: {
                required_approving_review_count: 1
              },
              restrictions: null
            });
