name: CII Best Practices

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sundays

# Минимальные необходимые разрешения
permissions:
  contents: read # для checkout и проверки файлов
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b6849436894e144dbce29d7d7fda2ae3bf9d8365 # v4
      
      - name: Setup Node.js
        uses: actions/setup-node@72476173717e9fa92b08abe87e9c9dc3a42dc0c8 # v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      - name: Install Syft
        run: |
          SYFT_EXPECTED_HASH="709ae9171e3d44e456a111943c341d0bf0fd2176b41af124d019823a70c34a3f"
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/v1.17.0/install.sh -o install.sh
          ACTUAL_HASH=$(shasum -a 256 install.sh | cut -d ' ' -f 1)
          if [ "$SYFT_EXPECTED_HASH" != "$ACTUAL_HASH" ]; then
            echo "Hash verification failed!"
            echo "Expected: $SYFT_EXPECTED_HASH"
            echo "Got: $ACTUAL_HASH"
            exit 1
          fi
          chmod +x install.sh
          ./install.sh -b /usr/local/bin v1.17.0
          rm install.sh

      - name: Generate SBOM with Syft
        run: syft dir:. -o cyclonedx-json > bom.json
        
#      - name: Run security audit
#        run: npm audit
        
      - name: Check for CHANGELOG
        run: |
          if [ ! -f CHANGELOG.md ]; then
            echo "CHANGELOG.md file is missing"
            exit 1
          fi
          
      - name: Check for documentation
        run: |
          if [ ! -f README.md ]; then
            echo "README.md file is missing"
            exit 1
          fi
          
      - name: Check for test coverage
        run: |
          npm run test:coverage || echo "No test coverage found"
          
      - name: Check for security policy
        run: |
          if [ ! -f SECURITY.md ]; then
            echo "SECURITY.md file is missing"
            exit 1
          fi
