name: CII Best Practices

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sundays

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM with Syft
        run: syft dir:. -o cyclonedx-json > bom.json
        
#      - name: Run security audit
#        run: npm audit
        
      - name: Check for CHANGELOG
        run: |
          if [ ! -f CHANGELOG.md ]; then
            echo "CHANGELOG.md file is missing"
            exit 1
          fi
          
      - name: Check for documentation
        run: |
          if [ ! -f README.md ]; then
            echo "README.md file is missing"
            exit 1
          fi
          
      - name: Check for test coverage
        run: |
          npm run test:coverage || echo "No test coverage found"
          
      - name: Check for security policy
        run: |
          if [ ! -f SECURITY.md ]; then
            echo "SECURITY.md file is missing"
            exit 1
          fi
