# Security Notes
# Only selected Actions are allowed within this repository.
# REVIEWERS, please always double-check security practices before merging a PR that contains Workflow changes!!
# AUTHORS, please only use actions with explicit SHA references, and avoid using `@master` or `@main` references or `@version` tags.

name: Pull Request CI Label

on:
  pull_request_target:
    branches:
      - main
    types:
      - labeled
      - unlabeled

defaults:
  run:
    working-directory: ./

permissions:
  pull-requests: write
  contents: read

jobs:
  remove_pull_request_label:
    name: Remove Pull Request Label
    # Только если добавлена определенная метка
    if: github.event.label.name == 'github_actions:pull-request'
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: Remove GitHub Actions Label
        uses: actions-ecosystem/action-remove-labels@f5dccab59b9ed79c1a5ddd2ab6d8771449b0250f # v1.3.0
        with:
          labels: github_actions:pull-request

  notify_on_remove:
    name: Notify on Label Remove
    needs: remove_pull_request_label
    runs-on: ubuntu-latest
    steps:
      - name: Create Comment
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: 'Метка `github_actions:pull-request` была автоматически удалена. Для повторного запуска workflow, пожалуйста, добавьте метку снова.'
            })
